url parsing fix to account for different urls in versions of python
Azure/azure-python-devtools pull request #31
Opened 2017-09-05 20:57 UTC by williexu

-added same fix from sdk to python devtools
-subs `//` for `/` in middle of url

2017-09-05 20:58 UTC, msftclas commented
@williexu,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-09-05 22:50 UTC, lmazuel approved these changes
LGTM!

2017-09-06 16:32 UTC, troydai requested changes

2017-09-06 16:32 UTC, troydai commented on src/azure_devtools/scenario_tests/base.py
> +
Please put this in a separate recording processor and add it to the other recording processors. The actual logic of altering the recording should not be placed in the framework.

2017-09-06 21:22 UTC, troydai approved these changes
Rename the class. Otherwise looks good.

2017-09-06 21:22 UTC, troydai commented on src/azure_devtools/scenario_tests/recording_processors.py
> +class SlashReplacer(RecordingProcessor):
A better name is like `RequestUrlNormalizer`

2017-09-06 22:00 UTC, merged